dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
env:
  - VERSION=1.0
install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-tests.txt
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - make before-dist version=${VERSION}.${TRAVIS_BUILD_NUMBER}
deploy:
  provider: pypi
  username: __token__
  password:
    secure: TxfQwN/4/4MHNsro3stTiPwIj75O798Z0WztYnMGtK0If9RTyWsIrbd0PTRMGz6wbEV+wYEfm81jBcfC84BAjokx/6sepA/wW/7YMvGnZEUd9asEZ/p1hr3LVJQtqaSqhdo1kndSsuA4d/OhJtaodDA6m6lS1f6TS8RZViNBTRjcT+j0QEtxuiInkD8s5uAXHfjuA9w4/4x9ysUyzP4pZvdi65KpXhRlXr5SiK6qivOVNlG/Dfdd3FCpUk9PCawuQvWx5kocDvahG6oXDcRCiAsNE5+dTkEweoqNZsCn4h+Hjaj7qXeCzPdQfDmjqJZcDjBBSUdHyUw+vZnrvtTdErvO0XilknhBUSDXH9vLUkN9Ggnd/xaBRSqywk0jyT5KFLm8M91SXOS92XnmTio32D4NyRgdCVcwlu4WztQoTpIHR+sJYKruPbY50+Aw1iynAaxWZXmOUfPSYKhwTlIUpGh9MY+2QSMgRgwi5j3r5cDZlRQGQaDNfUQyduR6Cx6KPKkQ/lrU0t1GaHU2Ee54l/bGI7/vUTMxYFBSPFmfISbm3ameKt1iJyIKyKpV/lqYPj8CeQRsIQ53cafiZYe90RlfMD+qdACvE0PgVkMV636CSra/wMJu6ZFmd54TThpPRnq2MQf4SOXZh9N3EynRGGsb0fqO11X/omKGb2X1Rb4=
  edge: true
  distributions: sdist bdist_wheel
  on:
    repo: hellofresh/eks-rolling-update
    branch: master
